
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Spinner from "~/components/Spinner";

export default function Home() {
  // petfinder API set up
  // https://www.youtube.com/watch?v=RCg1KKs8v9I
  const router = useRouter();

  useEffect(() => {
      void router.push("/dogs");
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>{`JC's Dog Adoption`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-center`}
      >
        <Spinner fullscreen={true} />
      </main>
    </>
  );
}